### PR TITLE
Raetskaya First Java task

### PR DESCRIPTION
**Pull request by Raetskaya**
First task

### CODE REVIEW

**Comment by Raetskaya** [comment]
> You need only SimpleJavaProject/src/main/java/ana_raetcaia/Main.java file Other files should be removed My suggestion is to have two different projects for two different courses.

I can remove other files in Github, click in the upper right corner  - Delete file? 
What you mean about two different courses? there is one task, but I don’t know where the other files came from

**Comment by Raetskaya** [comment]
> You need only SimpleJavaProject/src/main/java/ana_raetcaia/Main.java file Other files should be removed My suggestion is to have two different projects for two different courses.

Fixed.

**Review by dgrimaliuc — CHANGES_REQUESTED** [review]
Please remove target folder
and click on update your branch to get new changes from master

**Review by dgrimaliuc — CHANGES_REQUESTED** [review]
Please remove target folder and 
Please update your branch,
pull last changes from master or do rebase.

**Review by dgrimaliuc — APPROVED** [review]

**Pull request merged**
