### PR TITLE
Cristina Savrin third java task

### PR DESCRIPTION
**Pull request by CristinaSavrin**
Cristina Savrin third java task

### CODE REVIEW

**Review by dgrimaliuc — CHANGES_REQUESTED** [review]
Please update your branch, 
pull last changes from master or do rebase.

**Comment by CristinaSavrin** [comment]
Done.

**Review by dgrimaliuc — CHANGES_REQUESTED** [review]
Please mve your changes out of SimpleJavaProject folder and after remove this folder

**Review by dgrimaliuc — APPROVED** [review]
Very good, approved!

**Comment by CristinaSavrin** [comment]
Thank you.

**Comment by CristinaSavrin** [comment]
> Very good, approved!

Thank you.

**Pull request merged**
